BEGIN
IF DATAPERIOD=0 THEN MINBI:='FBASE.VAR2#MIN1';
IF DATAPERIOD=1 THEN MINBI:='FBASE.VAR2#MIN5';
IF DATAPERIOD=2 THEN MINBI:='FBASE.VAR2#MIN30';
IF DATAPERIOD=3 THEN MINBI:='FBASE.VAR2#MIN60';
IF DATAPERIOD=4 THEN MINBI:='FBASE.VAR2#DAY';
IF DATAPERIOD=5 THEN MINBI:='FBASE.VAR2#DAY';
IF DATAPERIOD=6 THEN MINBI:='FBASE.VAR2#WEEK';
IF DATAPERIOD=7 THEN MINBI:='FBASE.VAR2#MONTH';
IF DATAPERIOD=8 THEN MINBI:='FBASE.VAR2#YEAR';
VAR001:='FBASE.VAR2#MIN30';
IF DATATYPE=3 THEN VAR001:='FBASE.VAR2#MIN60';
IF DATATYPE=4 THEN VAR001:='FBASE.VAR2#DAY';
VAR1:='CHZHSHCH@KXIAN';
VAR2:='CHZHSHCH@BI';{处理笔关系}
VAR3:='CHZHSHCH@TONGJI'(MINBI);{同级别分解}
ZG:='CHZHSHCH@ZG'(VAR3);//一定要先调用ZG
ZD:='CHZHSHCH@ZD'(VAR3);
VAR1:='CHZHSHCH@KXIAN';
VAR2:='CHZHSHCH@BI';
VAR4:=BARSLAST(VAR001<>0);
TJ1:=REF(VAR001,VAR2)=-1;  //上级别是底
VAR5:=SUM(ABS(VAR2),VAR2);
TJ2:=VAR5=1; //第一个回调才算
TJ3:=COUNT(ABS(VAR3),BARSLAST(VAR3=-1))=0;
ZSWZ:=BARSLAST(ZG>ZD);
TJ4:=COUNT(ZG>ZD,BARSLAST(VAR3=-1))>0;
TJ5:=COUNT(VAR2=1,BARSLAST(VAR2=-1))=1;
TJ6:=COUNT(VAR2=1,ZSWZ-1)=1;
TJ7:=REF(L,BARSLAST(VAR2=1))>REF(ZG,BARSLAST(ZG>ZD));
NOT(ZG>ZD) AND TJ3 AND TJ4 AND TJ5 AND TJ6 AND TJ7;
END;